site_name: Plant-IA
site_description: Librería para estructurar prompts dinámicos en español.
theme:
  name: material
  language: es
nav:
  - Inicio: index.md
  - Guía rápida: guia.md
  - Ejemplos: ejemplos.md
  - Contribuir: contribuir.md
  - Roadmap: roadmap.md