site_name: Plant-IA
site_description: Librería para estructurar prompts dinámicos en español.
theme:
  name: material
  language: es
nav:
  - Inicio: docs/index.md
  - Guía rápida: docs/guia.md
  - Ejemplos: docs/ejemplos.md
  - Contribuir: docs/contribuir.md
  - Roadmap: docs/roadmap.md